#! /usr/bin/env python

Import( 'env' )

env = env.Copy()

env.PrependUnique( CPPPATH=["#/src", "#/external/dbus/include"] )
env.PrependUnique( LIBPATH=[env['build_base']+"src", env['build_base']+"external/dbus"] )
env.PrependUnique( LIBS=["ffado", "dbus-c++"] )

if not env.GetOption( "clean" ):
	env.MergeFlags( env["DBUS1_FLAGS"] )
	env.MergeFlags( env['LIBRAW1394_FLAGS'] )
	env.MergeFlags( env['LIBXML26_FLAGS'] )

#
# deactivate as they don't seem ported to the new api: test-extplugcmd, test-mixer, test-volume
#
#for app in ["test-ffado", "test-extplugcmd", "test-fw410", "test-volume", "test-mixer", "test-cycletimer", "test-timestampedbuffer", "test-ieee1394service", "test-streamdump"]:

for app in ["test-fw410", "test-cycletimer", "test-timestampedbuffer", "test-ieee1394service", "test-streamdump"]:
    env.Program( target=app, source = app+".cpp" )

env.Program( target="test-sytmonitor", source = env.Split( "test-sytmonitor.cpp SytMonitor.cpp" ) )

env.Xml2Cpp_Proxy('controlclient-glue.h', 'control-interface.xml')
env.Program( target="test-dbus", source = env.Split( "test-dbus.cpp controlclient.cpp" ) )

env.Xml2Cpp_Adaptor('controlserver-glue.h', 'control-interface.xml')
env.Program( target="test-dbus-server", source = env.Split( "test-dbus-server.cpp controlserver.cpp" ) )
env.Program( target="test-ffado", source = env.Split( "test-ffado.cpp controlserver.cpp" ) )


env.SConscript( dirs="streaming", exports="env" )

