.TH FFADO-DICE-FIRMWARE 1 27-Mar-2012 "ffado-dice-firmware"
.SH NAME
ffado-dice-firmware \- firmware download application for DICE-based devices
.SH SYNOPSIS
.BI "ffado-dice-firmware [OPTION...]
.sp
.SH DESCRIPTION
.B ffado-dice-firmware
permits firmware updates to be made to DICE-based devices under 
Linux.
.sp
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Display brief usage information and exit
.TP  
.B "\-p, \-\-port=NUM"
Specify use of IEEE1394 port
.I NUM
.TP   
.B "\-v, \-\-verbose=LEVEL"
Produce verbose output.  The higher the
.I LEVEL
the more verbose the messages.  The some verbose messages may only be
available of FFADO was compiled with debugging enabled.
.TP
.B "\-d, \-\-delete=IMAGENAME"
Delete image by name.
.TP
.B "\-e, \-\-dump=FILENAME"
Extract current DICE device flash contents into file
.I FILENAME
.TP
.B "\-f, \-\-flash=FILENAME"
Write firmware file
.I FILENAME
to DICE device.
.TP
.B "\-i, \-\-image-info"
Show detailed information about each image within the firmware on the
device.
.TP
.B "\-m, \-\-flash-info"
Show information about the flash memory on the device.
.TP
.B "\-s, \-\-dice-info"
Show DICE image vendor and product information.
.TP
.B "\-t, \-\-test OPERATION"
Invoke a test/debug operation.  Possible 
.I OPERATIONs
are 1 (POKE, write to address) and 2 (PEEK, read from address).  Refer to
the source code for further information.
.TP
.B "\-n, \-\-node NODE"
Specify the node to operate on.
.sp
.SH NOTES
Manipulating firmware can cause your device to stop working.  The FFADO
project accepts no responsibility if this occurs as a result of using this
tool.
