#! /usr/bin/env python

Import( 'env' )

env = env.Copy()

env.AppendUnique( CPPPATH=["#/src"] )
env.AppendUnique( LIBPATH=["#/src"] )
env.AppendUnique( LIBS=["ffado"] )

#env.AppendUnique( CCFLAGS=['-DENABLE_BEBOB'] )

for app in env.Split( "teststreaming teststreaming2 teststreaming3 testmidistreaming1" ):
	env.Program( target=app, source = [ app+".c", "debugtools.c" ] )


