#! /usr/bin/env python

Import( 'env' )

env = env.Copy()

#env.AppendUnique( CPPPATH=["#/src"] )
#env.AppendUnique( LIBPATH=["#/src"] )
#env.AppendUnique( LIBS=["ffado"] )

for app in ["mixer_phase24.ui","mixer_phase88.ui"]:
	#env.PyUIC( target=app.replace(".","")+".py", source=app )
	env.Command( target=app.replace(".","")+".py", source=app, action="pyuic $SOURCE > $TARGET" )


