#! /usr/bin/env python

Import( 'env' )

if env.has_key('HAVE_PYUIC') and env['HAVE_PYUIC']:

	env = env.Copy()

	for app in ["mixer_phase24.ui","mixer_phase88.ui"]:
		env.Command( target=app.replace(".","")+".py", source=app, action="pyuic $SOURCE > $TARGET" )


