#!/usr/bin/python
#
# Copyright (C) 2007-2008 Arnold Krille
# Copyright (C) 2007-2008 Pieter Palmers
#
# This file is part of FFADO
# FFADO = Free Firewire (pro-)audio drivers for linux
#
# FFADO is based upon FreeBoB.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
import os
from string import Template

Import( 'env' )

if env.has_key('PYUIC'):
	e = env.Clone()

	e['MIXERAPPS'] = [ 'phase24', 'phase88', 'saffirepro', 'saffire',
	                   'saffirele', 'af2', 'bcoaudio5', 'edirolfa66',
	                   'mackie_generic', 'quatafire', 'motu', 'generic' ]
	#
	# For the ffadomixer.in
	e['PYTHONDIR'] = Template( os.path.join( e['SHAREDIR'], 'python' ) ).safe_substitute( e )
	# For the installation of the stuff
	e['pythondir'] = Template( os.path.join( e['sharedir'], 'python' ) ).safe_substitute( e )

	for m in e['MIXERAPPS']:
		app = "mixer_" + m
		if os.path.exists( app+".ui" ):
			e.PyUIC( source=app+".ui", target=app+"ui.py" )
			e.Install( "$pythondir", app+"ui.py" )
		e.Install( "$pythondir", app+".py" )

	e.ScanReplace( "ffadomixer.in" )
	e.Depends( "ffadomixer", "SConscript" )
	e.Install( "$bindir", "ffadomixer" )

